server:
  port: 80
 
spring:
  application:
    name: BookMyTicketAPIGateway
  config:
    import: configserver:http://localhost:8080
  cloud:
    gateway:
      routes:
        - id: BookMyTicketService
          uri: lb://BookMyTicketService
          predicates:
            - Path=/user/**
        - id: MovieService
          uri: lb://MovieService
          predicates:
            - Path=/movies/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - Content-Type
              - Authorization
              - Origin
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
#Authorization, x-xsrf-token, Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, " +
#            ", Access-Control-Request-Method, Access-Control-Request-Headers
        